# Generated by Django 3.2.4 on 2021-06-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('cust_name', models.CharField(max_length=60)),
                ('email_id', models.EmailField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=15)),
                ('town_or_city', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
