# Generated by Django 3.2.4 on 2021-06-28 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gadgets', '0004_auto_20210620_0114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=150)),
                ('review_description', models.TextField()),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gadget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gadgets.gadgetattr')),
            ],
        ),
    ]
