# Generated by Django 3.2.4 on 2021-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgetattr',
            name='dimensions',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gadgetattr',
            name='imageurls',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
