# Generated by Django 3.2.4 on 2021-06-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_auto_20210614_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gadgetName',
        ),
        migrations.AddField(
            model_name='gadgetattr',
            name='name',
            field=models.CharField(default=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gadgetattr',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=7),
            preserve_default=False,
        ),
    ]
